### Create new connection
POST {{host}}/api/connections
Content-Type: application/json

{
  "name": "Local PG",
  "host": "db",
  "port": 5432,
  "databaseName": "PgExplorer",
  "username": "postgres",
  "password": "postgres"
}
