### Test connection
POST {{host}}/api/connections/test
Content-Type: application/json

{
  "host": "localhost",
  "port": 5432,
  "databaseName": "PgExplorer",
  "username": "postgres",
  "password": "postgres"
}

###