### Update connection
PUT {{host}}/api/connections/1
Content-Type: application/json

{
  "name": "Updated Connection",
  "host": "127.0.0.1",
  "port": 5432,
  "databaseName": "postgres",
  "username": "postgres",
  "password": "secret"
}
