### Update connection
PUT {{host}}/api/connections/2
Content-Type: application/json

{
  "name": "Updated Connection",
  "host": "db",
  "port": 5432,
  "databaseName": "PgExplorer",
  "username": "postgres",
  "password": "postgres"
}
