// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pg.Explorer.Infrastructure.Database;

#nullable disable

namespace Pg.Explorer.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PgExplorerDbContext))]
    [Migration("20250911154449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "QueryStatus", new[] { "Success", "Error" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "QueryType", new[] { "Read", "Write", "Delete", "Update" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pg.Explorer.Domain.ConnectionConfigs.ConnectionConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("database_name");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_password");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_connection_configs");

                    b.ToTable("connection_configs", (string)null);
                });

            modelBuilder.Entity("Pg.Explorer.Domain.Queries.Entities.QueryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AffectedRows")
                        .HasColumnType("integer")
                        .HasColumnName("affected_rows");

                    b.Property<long>("ConnectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("connection_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<TimeSpan>("ExecutionTime")
                        .HasColumnType("interval")
                        .HasColumnName("execution_time");

                    b.Property<string>("QueryBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_body");

                    b.Property<string>("QueryStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_status");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_type");

                    b.HasKey("Id")
                        .HasName("pk_queries");

                    b.HasIndex("ConnectionId")
                        .HasDatabaseName("ix_queries_connection_id");

                    b.ToTable("queries", (string)null);
                });

            modelBuilder.Entity("Pg.Explorer.Domain.Queries.Entities.QueryEntity", b =>
                {
                    b.HasOne("Pg.Explorer.Domain.ConnectionConfigs.ConnectionConfig", "Connection")
                        .WithMany("Queries")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queries_connection_configs_connection_id");

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("Pg.Explorer.Domain.ConnectionConfigs.ConnectionConfig", b =>
                {
                    b.Navigation("Queries");
                });
#pragma warning restore 612, 618
        }
    }
}
