// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pg.Explorer.Infrastructure.Database;

#nullable disable

namespace Pg.Explorer.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PgExplorerDbContext))]
    partial class PgExplorerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pg.Explorer.Domain.ConnectionConfigurations.ConnectionConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("database_name");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("encrypted_password");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_connection_configs");

                    b.ToTable("connection_configs", (string)null);
                });

            modelBuilder.Entity("Pg.Explorer.Domain.Queries.Entities.QueryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AffectedRows")
                        .HasColumnType("integer")
                        .HasColumnName("affected_rows");

                    b.Property<long?>("ConnectionConfigurationId")
                        .HasColumnType("bigint")
                        .HasColumnName("connection_configuration_id");

                    b.Property<long>("ConnectionId")
                        .HasColumnType("bigint")
                        .HasColumnName("connection_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<JsonDocument>("ExecutionResult")
                        .HasColumnType("jsonb")
                        .HasColumnName("execution_result");

                    b.Property<TimeSpan>("ExecutionTime")
                        .HasColumnType("interval")
                        .HasColumnName("execution_time");

                    b.Property<string>("QueryBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("query_body");

                    b.Property<int>("QueryStatus")
                        .HasColumnType("integer")
                        .HasColumnName("query_status");

                    b.Property<int>("QueryType")
                        .HasColumnType("integer")
                        .HasColumnName("query_type");

                    b.HasKey("Id")
                        .HasName("pk_queries");

                    b.HasIndex("ConnectionConfigurationId")
                        .HasDatabaseName("ix_queries_connection_configuration_id");

                    b.ToTable("queries", (string)null);
                });

            modelBuilder.Entity("Pg.Explorer.Domain.Queries.Entities.QueryEntity", b =>
                {
                    b.HasOne("Pg.Explorer.Domain.ConnectionConfigurations.ConnectionConfig", "ConnectionConfiguration")
                        .WithMany("Queries")
                        .HasForeignKey("ConnectionConfigurationId")
                        .HasConstraintName("fk_queries_connection_configs_connection_configuration_id");

                    b.Navigation("ConnectionConfiguration");
                });

            modelBuilder.Entity("Pg.Explorer.Domain.ConnectionConfigurations.ConnectionConfig", b =>
                {
                    b.Navigation("Queries");
                });
#pragma warning restore 612, 618
        }
    }
}
